# Generated by Django 4.0.4 on 2022-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['start_year']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='linkedln',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='labattendance',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='labattendance',
            name='linkedln',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='labattendance',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
        migrations.AddField(
            model_name='labattendance',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='linkedln',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='more_info',
            field=models.TextField(blank=True),
        ),
    ]
