# Generated by Django 4.0.4 on 2022-05-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_alter_doctor_subordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='subordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.doctor'),
        ),
    ]
