# Generated by Django 4.0.4 on 2022-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_remove_appointment_message_alter_patient_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugprescription',
            old_name='name',
            new_name='drug_name',
        ),
        migrations.AlterField(
            model_name='drugprescription',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
