# Generated by Django 4.0.4 on 2022-05-21 19:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_rename_name_drugprescription_drug_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
