# Generated by Django 4.0.4 on 2022-05-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
        ('Patient', '0004_alter_entry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.department'),
            preserve_default=False,
        ),
    ]
