# Generated by Django 4.0.4 on 2022-05-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
        ('Patient', '0005_entry_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='name',
        ),
        migrations.CreateModel(
            name='LabTestObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=160)),
                ('price', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Department.department')),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Patient.labtestobject'),
            preserve_default=False,
        ),
    ]
