# Generated by Django 4.0.4 on 2022-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_alter_admission_bed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date_of_discharged',
            field=models.DateField(blank=True, null=True),
        ),
    ]
