# Generated by Django 4.0.4 on 2022-05-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_remove_labtest_department_remove_labtest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugprescription',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Patient.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Patient.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtest',
            name='appointment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Patient.appointment'),
            preserve_default=False,
        ),
    ]
