# Generated by Django 4.0.4 on 2022-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_drugprescription_appointment_entry_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
