# Generated by Django 4.0.4 on 2022-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_labtest_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
