# Generated by Django 4.0.4 on 2022-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_alter_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True),
        ),
    ]
