# Generated by Django 4.0.4 on 2022-05-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_alter_admission_date_of_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='for_patient',
            new_name='patient',
        ),
        migrations.AlterUniqueTogether(
            name='admission',
            unique_together={('patient', 'date_of_admission')},
        ),
    ]
