# Generated by Django 4.0.4 on 2022-05-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
        ('Patient', '0012_rename_for_patient_admission_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='bed_number',
            field=models.OneToOneField(blank=True, limit_choices_to=models.Q(('status', 1)), null=True, on_delete=django.db.models.deletion.CASCADE, to='Department.bed'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(),
        ),
    ]
