# Generated by Django 4.0.4 on 2022-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0013_alter_admission_bed_number_alter_entry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=15),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
