# Generated by Django 4.0.4 on 2022-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_appointment_payment_status_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
