# Generated by Django 4.0.4 on 2022-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0016_appointment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(default='Teacher', max_length=20),
        ),
    ]
