# Generated by Django 4.0.4 on 2022-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_alter_department_about_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Occupied', 'Occupied')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
