# Generated by Django 4.0.4 on 2022-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_bed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Occupied', 'Occupied')], default=1, max_length=10),
        ),
    ]
